# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:

    # snagged this:
    # from here: https://stackoverflow.com/questions/12223176/how-to-inject-a-repository-into-a-service-in-symfony2
    app.ingredients_repository:
      class: Doctrine\ORM\EntityRepository
      factory: ["@doctrine.orm.entity_manager", getRepository]
      arguments: ['NoIncSimpleStorefrontBundle:Ingredient']

    app.recipes_repository:
      class: Doctrine\ORM\EntityRepository
      factory: ["@doctrine.orm.entity_manager", getRepository]
      arguments: ['NoIncSimpleStorefrontBundle:Recipe']

    app.ingredient_service:
      class: NoInc\SimpleStorefrontBundle\Services\IngredientService
      arguments: [ '@doctrine.orm.entity_manager', '@app.ingredients_repository' ]

    app.recipe_service:
      class: NoInc\SimpleStorefrontBundle\Services\RecipeService
      arguments: [ '@doctrine.orm.entity_manager', '@app.recipes_repository' ]

    app.shopping_cart_service:
      class: NoInc\SimpleStorefrontBundle\Services\ShoppingCartService
      arguments: ['@request_stack', '@doctrine.orm.entity_manager', '@security.token_storage']
