<?php

namespace NoInc\SimpleStorefrontBundle\Repository;

/**
 * IngredientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IngredientRepository extends \Doctrine\ORM\EntityRepository
{
    public function getIngredients() {
        $ingredients = $this->createQueryBuilder('ingredient')
                     ->addSelect('ingredient')
                     ->getQuery()
                     ->getResult();
        return $ingredients;
    }
}
